---
substitutions:
  id_prefix: ratgdov25
  friendly_name: "ratgdov2.5"
  uart_tx_pin: D1
  uart_rx_pin: D2
  input_obst_pin: D7
  status_door_pin: D0
  status_obstruction_pin: D8
  dht_pin: D5

web_server:

esphome:
  name: ${id_prefix}
  friendly_name: ${friendly_name}
  name_add_mac_suffix: true
  project:
    name: ratgdo.esphome
    version: "2.5"

esp8266:
  board: d1_mini
  restore_from_flash: true

dashboard_import:
  package_import_url: github://juanboro/esphome-ratgdo/jonboard_esp8266_d1_mini_secplusv1.yaml@main

packages:
  remote_package:
    url: https://github.com/juanboro/esphome-ratgdo
    files: [base_secplusv1.yaml]
    refresh: 1s

# Sync time with Home Assistant.
time:
  - platform: homeassistant
    id: homeassistant_time

api:
  id: api_server

ota:

improv_serial:

wifi:
  ap:

logger:


